export { UserProductPage } from "./Product/Product.page";
export { UserProfilePage } from "./Profile/Profile.page";
export { UserQuantityPage } from "./Quantity/Quantity.page";
export { UserOrdersPage } from "./Orders/Orders.page";
export { UserWishListPage } from "./WishList/WishList.page";
export { UserSettingPage } from "./Setting/Setting.page";
export { UserExitPage } from "./Exit/Exit.page";
export { ProtectedOrdersPage } from "./ProtectedOrders/ProtectedOrders.page";
export { UserCategoryPage } from "./Ccategory/Category.page"
export { UsersListPage } from "./Users/Users.page"