export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_QUANTITY = 'ADJUST_QUANTITY';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const GET_BASKET_LENGTH = 'GET_BASKET_LENGTH';
export const GET_ITEM_FROM_CART = 'GET_ITEM_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';